"""Add drawing_filename to WIRSession

Revision ID: 2729abf3c740
Revises: e8c958c87cb8
Create Date: 2026-03-09 12:27:17.795442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2729abf3c740'
down_revision: Union[str, None] = 'e8c958c87cb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wir_sessions', sa.Column('drawing_filename', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wir_sessions', 'drawing_filename')
    # ### end Alembic commands ###
