"""Initial migration

Revision ID: 38638f6725dc
Revises: 
Create Date: 2026-03-14 12:01:35.567265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '38638f6725dc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wir_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('session_name', sa.String(), nullable=True),
    sa.Column('master_discipline', sa.String(), nullable=True),
    sa.Column('master_work_type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('current_step', sa.Integer(), nullable=True),
    sa.Column('state', sa.JSON(), nullable=True),
    sa.Column('itp_filename', sa.String(), nullable=True),
    sa.Column('wir_sample_filename', sa.String(), nullable=True),
    sa.Column('mes_filename', sa.String(), nullable=True),
    sa.Column('drawing_filename', sa.String(), nullable=True),
    sa.Column('grid_lines', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('levels', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('zone', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wir_sessions_id'), 'wir_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_wir_sessions_session_id'), 'wir_sessions', ['session_id'], unique=True)
    op.create_table('checklist_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('item_number', sa.String(), nullable=True),
    sa.Column('item_text', sa.String(), nullable=True),
    sa.Column('acceptance_criteria', sa.String(), nullable=True),
    sa.Column('control_point', sa.String(), nullable=True),
    sa.Column('procedure_text', sa.String(), nullable=True),
    sa.Column('safety_text', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['wir_sessions.session_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checklist_items_id'), 'checklist_items', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_checklist_items_id'), table_name='checklist_items')
    op.drop_table('checklist_items')
    op.drop_index(op.f('ix_wir_sessions_session_id'), table_name='wir_sessions')
    op.drop_index(op.f('ix_wir_sessions_id'), table_name='wir_sessions')
    op.drop_table('wir_sessions')
    # ### end Alembic commands ###
