"""Add Step 2 fields

Revision ID: 4ef965297d57
Revises: 55d8f0b4186f
Create Date: 2026-03-08 14:48:44.927644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ef965297d57'
down_revision: Union[str, None] = '55d8f0b4186f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checklist_items', sa.Column('procedure_text', sa.String(), nullable=True))
    op.add_column('checklist_items', sa.Column('safety_text', sa.String(), nullable=True))
    op.add_column('wir_sessions', sa.Column('current_step', sa.Integer(), nullable=True))
    op.add_column('wir_sessions', sa.Column('mes_filename', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wir_sessions', 'mes_filename')
    op.drop_column('wir_sessions', 'current_step')
    op.drop_column('checklist_items', 'safety_text')
    op.drop_column('checklist_items', 'procedure_text')
    # ### end Alembic commands ###
