"""Add session_name column

Revision ID: 55d8f0b4186f
Revises: 
Create Date: 2026-03-08 13:19:57.762981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '55d8f0b4186f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wir_sessions', sa.Column('session_name', sa.String(), nullable=True))
    op.drop_column('wir_sessions', 'extracted_checklist')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wir_sessions', sa.Column('extracted_checklist', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('wir_sessions', 'session_name')
    # ### end Alembic commands ###
