"""Add master_discipline and master_work_type to WIRSession

Revision ID: 8680af3ceb2f
Revises: 2729abf3c740
Create Date: 2026-03-09 11:16:15.098014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8680af3ceb2f'
down_revision: Union[str, None] = '2729abf3c740'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wir_sessions', sa.Column('master_discipline', sa.String(), nullable=True))
    op.add_column('wir_sessions', sa.Column('master_work_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wir_sessions', 'master_work_type')
    op.drop_column('wir_sessions', 'master_discipline')
    # ### end Alembic commands ###
