"""Add all_drawing_data column to WIRSession

Revision ID: ab5425e1a876
Revises: 38638f6725dc
Create Date: 2026-03-14 15:00:11.800999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ab5425e1a876'
down_revision: Union[str, None] = '38638f6725dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wir_sessions', sa.Column('all_drawing_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wir_sessions', 'all_drawing_data')
    # ### end Alembic commands ###
