"""Add drawing and location fields to WIRSession

Revision ID: e8c958c87cb8
Revises: 4ef965297d57
Create Date: 2026-03-09 12:26:43.854986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e8c958c87cb8'
down_revision: Union[str, None] = '4ef965297d57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wir_sessions', sa.Column('grid_lines', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('wir_sessions', sa.Column('levels', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('wir_sessions', sa.Column('zone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wir_sessions', 'zone')
    op.drop_column('wir_sessions', 'levels')
    op.drop_column('wir_sessions', 'grid_lines')
    # ### end Alembic commands ###
